version: '3'
services:
  akka-api:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    networks:
      - my-network
    command: ["sbt", "clean", "run"]

networks:
  my-network: