version: '3'
services:
  akka-api:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    networks:
      - my-network
    command: [ "sbt", "-J-Xms256m", "-J-Xmx412m", "-J-XX:+UseG1GC", "-J-XX:MaxGCPauseMillis=100", "-J-XX:ParallelGCThreads=2", "run" ]
networks:
  my-network: